version: 2
jobs:
  build:
    machine: true
    steps:
    - checkout
    - run:
        name: Build Docker image for running python tests
        command: docker build -t plaid-python .
    - run:
        name: Run python tests in Docker
        command: docker run --rm -e CLIENT_ID=**REDACTED** -e SECRET=**REDACTED** plaid-python
    - store_test_results:
        path: /tmp/circleci-test-results
        
  build_arm:
   machine:
      image: ubuntu-2004:202101-01
   resource_class: arm.medium
   working_directory: ~/dash

   steps:
    - checkout
    - run:
        name: Build Docker image for running python tests
        command: docker build -t plaid-python .
    - run:
        name: Run python tests in Docker
        command: docker run --rm -e CLIENT_ID=**REDACTED** -e SECRET=**REDACTED** plaid-python
    - store_test_results:
        path: /tmp/circleci-test-results
        
